### ISSUE TITLE
apm cannot download module 

### ISSUE THREAD

**Issue by fdedraco** [atom/atom.io#163]
i need to change the url from www.atom.io to atom.io (notice that there's no www) how do i do that?

**Comment by rsese** [comment]
Thanks for reaching out - can you share more details about the issue?  What are you trying to install with apm?  Can you share the exact command you're running?  And why do you need to change the URL?

Any other information about what you're trying to do and why would be super helpful.

**Comment by fdedraco** [comment]
my dns is government/ isp locked and cannot resolve www.atom.io into atom.io hence cannot download the packages from the website. apm cannot reach the server that way.

**Comment by rsese** [comment]
Ahhh gotcha - there's no setting in apm that will let you do this as far as I know.   If it's an issue with your ISP perhaps you can use alternate DNS or temporarily connect to another provider if you need to install packages (I know it's not ideal)?

Going to close this out since I don't believe it's actionable on our end but let me know if I mis-understood anything.

**Comment by fdedraco** [comment]
so, should i post "bug" at apm repo? because the hardcoded url doesn't match?
thanks for the reply
