### ISSUE TITLE
Use newer CDN endpoint

### ISSUE THREAD

**Issue by tambry** [atom/atom.io#164]
Currently `github-atom-io-herokuapp-com.global.ssl.fastly.net` is used to serve static resources. Simply changing it to `github-atom-io-herokuapp-com.freetls.fastly.net` would enable HTTP/2 and IPv6, with no extra work required. See [Fastly Free TLS documentation](https://docs.fastly.com/guides/securing-communications/setting-up-free-tls#support-for-http2-ipv6-and-tls-12).

**Comment by queerviolet** [comment]
I tried this out and it looks good. Great suggestion, thanks! 👍🏽

**Comment by queerviolet** [comment]
Okay, I haven't been able to track down why the octicon font is still being served from `global.ssl`, rather than `freetls`. I have a vague sense that it might be a cache somewhere along the way and we'll see those requests stop eventually. In any case, I just added `global.ssl` to the CSP and now this looks good.

**Comment by tambry** [comment]
I'm seeing those resources from `global.ssl` being loaded from this CSS file:
```
https://github-atom-io-herokuapp-com.freetls.fastly.net/assets/application-80666191c65fb127e8528f18053606c1.css
```
For example:
```
background-image: url(//github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/index-rocket-9359158bb67101ecc5c5ea3e2affc49b.svg)
```
