### ISSUE TITLE
Issue with the Site Colour Pattern

### ISSUE THREAD

**Issue by aayusharyan** [atom/atom.io#174]
On the landing page, let us divide it into three sections.
First section looks perfect with everything yellow shade.
<img width="1301" alt="screenshot 2018-11-09 at 5 11 43 pm" src="https://user-images.githubusercontent.com/16634228/48260745-a01c8c00-e442-11e8-84ff-c58589c18b8e.png">

---

Next Section has a colour mismatch:
Current:
<img width="1301" alt="screenshot 2018-11-09 at 5 11 49 pm" src="https://user-images.githubusercontent.com/16634228/48260762-b32f5c00-e442-11e8-959a-7acc8a393b37.png">

Suggestion:
<img width="1301" alt="screenshot 2018-11-09 at 5 14 38 pm" src="https://user-images.githubusercontent.com/16634228/48260836-f7226100-e442-11e8-9718-5c55492d44fc.png">

---

similarly, next section...
Current:
<img width="1301" alt="screenshot 2018-11-09 at 5 11 55 pm" src="https://user-images.githubusercontent.com/16634228/48260858-06091380-e443-11e8-8472-f1587ba0152d.png">

Suggestion:
<img width="1301" alt="screenshot 2018-11-09 at 5 16 04 pm" src="https://user-images.githubusercontent.com/16634228/48260889-2a64f000-e443-11e8-98c4-63db18c9f24c.png">

---
Comments are welcome.

**Comment by rsese** [comment]
Thanks for the suggestions (and for the screenshots of what you're picturing)!

We've passed along your suggestion to our design folks - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.

**Comment by simurai** [comment]
@aayusharyan That's a great suggestion. 👍

**Comment by simurai** [comment]
This is now live on [atom.io](https://atom.io/). 🎨
