### ISSUE TITLE
Settings Pane opening up in odd place

### ISSUE THREAD

**Issue by KeithETruesdell** [atom/atom.io#175]
This has happened a few times, not sure what causes this, but the only 'solution' I have found is to do a clean install.

Normally the settings pane will open up in the main editor area.  Either by using Ctrl+, or File --> Settings (or any other way to get to that pane).
However, sometimes (and once it happens once it won't stop), this will open in what appears to be the "navigation pane".  I don't think its truly the navigation pane though, but another pane on top of the navigation pane.  
The only way to get out of this "settings" page is to then right-click on the area and select "close pane" (or Ctrl-W).
You can't get to the tab at the top, you can't move the pane or tab somewhere else.  

It almost seems as if this is the result of a bad package installed, but I don't know what package.  I have tried to uninstall packages and/or disable them to get it back to "normal".  But to no avail. 

Currently this is on the latest version of Atom (1.32.2) for windows 64 on Windows 10.  This has happened on 3 different Windows machines that I have used.  This has also happened on several versions of Atom, since about 1.2x? (I didn't really take note at the time, just did a Google search with no results and did a fresh reinstall).

Its hard to reproduce as I can't "undo" it without a clean reinstall.  I don't do anything out of the ordinary or different, its just one time seemingly random time I am looking to do something in my settings and I will hit Ctrl+, and then it pops up over the navigation pane.

Regular window
![image](https://user-images.githubusercontent.com/2074768/48561345-bea8da00-e8bd-11e8-83db-074ad8a7a8f7.png)

Settings page
![image](https://user-images.githubusercontent.com/2074768/48562326-f6b11c80-e8bf-11e8-930b-0f9b06ae2d15.png)

Trying to close the settings page
![image](https://user-images.githubusercontent.com/2074768/48562261-cff2e600-e8bf-11e8-8b4c-d0ab9fb6b937.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

-----

Specifically, the template directs you to try things in the [debugging guide of the Atom Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/), which it doesn't seem that you've attempted from your description.

**Comment by lee-dohm** [comment]
I apologize, this repository doesn't have an issue template like most of the others, including [atom/atom](https://github.com/atom/atom) and [atom/settings-view](https://github.com/atom/settings-view), which would be better places to report this issue. This repository is for reporting problems with the https://atom.io website itself, not problems with the Atom application. When you open your new issue, please use the https://github.com/atom/settings-view repository.
