### ISSUE TITLE
Coding format problem

### ISSUE THREAD

**Issue by Qk87** [atom/atom.io#190]
When I modify a file in GBK encoding format, even if I have selected the GBK encoding format in the settings, the default is UTF-8 encoding when previewing in staged changes, and it cannot be modified, which leads to my Chinese annotation display. For garbled, I hope you can solve this problem, because I have to use the GBK encoding format, and batch conversion encoding format is too much trouble.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

In addition to using the issue template, please open the issue in the https://github.com/atom/atom repository - we use multiple repositories to keep the work items tied to the code they apply to (we might end up moving the issue, but we can start with atom/atom). This helps the maintainers spend more time working directly on Atom and less time triaging issues.
