### ISSUE TITLE
Can't Login to GitHub in Atom after changing my GitHub username

### ISSUE THREAD

**Issue by garrett-lane** [atom/atom.io#192]
Hello. I recently changed my GitHub username. Since then, I have not been able to log into my GitHub account on Atom. I go through the normal steps and go to github.atom.io/login and it logs me in and I get an authorization code. I have tried multiples times but whenever I put it into Atom it just says, "Query errors reported. Could not resolve to a User with the username '(my old username)'."
I have tried updating Atom, reinstalling Atom, revoking Atom's access to my GitHub account and then re-granting access and I still get this same error. I have been getting this error for about 2-3 days now and I have been hoping it would go away after some restarts but apparently not. I'm not sure what else to try at this point and I would like to be able to use Atom again so I can get back to my projects.
![query error](https://user-images.githubusercontent.com/45501825/71566271-f2bc6b80-2a7b-11ea-863f-b674b3458eb9.PNG)

**Comment by lkashef** [comment]
Hey @garrett-lane, Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

When you open the new issue, please use the template, there will be links listed with tips (clearing cache, safe mode, etc) about improving writing the reproduction steps and properly debug atom problems.

Also consider the classic restart and install/re-install, when it comes to a problem that might look like a caching problem such solutions could be a time saver.

Also please make sure you open the issue on the right repo, in this case it's https://github.com/atom/github
