### ISSUE TITLE
broken "Package" link in documentation

### ISSUE THREAD

**Issue by stephenmathieson** [atom/atom.io#26]
in the [`PackageManager#enablePackage()` documentation](https://atom.io/docs/api/v1.0.7/PackageManager#instance-enablePackage), there's a broken link to [`Package`](https://atom.io/docs/api/v1.0.7/Package).

**Comment by izuzak** [comment]
Thanks for the report, @stephenmathieson :bow:

@kevinsawicki @nathansobo I'm _guessing_ this is because `Package` is [not marked as Essential nor Extended](https://github.com/atom/atom/blob/0a6da382cfdb130144c76595f204b78e3aaf1067/src/package.coffee#L17-L20), even though it has [methods which are marked as public APIs](https://github.com/atom/atom/blob/0a6da382cfdb130144c76595f204b78e3aaf1067/src/package.coffee#L635-L642). Would it be okay to mark this class as `Extended` so that it shows up in the docs? Or is there something else going on here?

**Comment by nathansobo** [comment]
@izuzak It is because the `Package` isn't marked as essential or extended. We could make it so, but the API docs on `Package` itself are a bit of a mess as well.

**Comment by kevinsawicki** [comment]
https://github.com/atom/atom/pull/7896

**Comment by nathansobo** [comment]
Now the hold up is reviewing the `Package` API and potentially trimming it back in any areas we aren't confident it's good. Since the package system is one of the messier areas of our codebase I'm reluctant to just make it public without reviewing it carefully.

**Comment by izuzak** [comment]
Closing this since https://github.com/atom/atom/pull/7896 was merged. The docs should refresh when the next Atom version is published -- let us know if that doesn't happen.
