### ISSUE TITLE
Update or remove the featured section for packages

### ISSUE THREAD

**Issue by danielbrodin** [atom/atom.io#56]
The featured section for packages never seem to be updated. If no one has the time to keep track of interesting packages I think it should be removed because it looks kind of bad having a featured section that never is updated in my opinion.

I don't look under themes that much, but I get a feeling that the featured themes is updated now and then?

**Comment by winstliu** [comment]
Looking at the list it's definitely different than it was a few months ago, so closing.

**Comment by iolsen** [comment]
I'll add that we realize this doesn't update often enough or in meaningful ways. We will improve it though it likely won't be super soon.

**Comment by jrial** [comment]
If I can throw in my 2 cents, it would be nice if that list were somehow customised based on how you use the editor. E.g. program a lot in C/C++, and more packages for those languages get shown.

On a fresh Atom, just a generic list of useful packages since there's nothing to base the suggestions on. But once the user installs some packages, the list should start showing more "related" packages, picked from a pool of packages which have been marked as "on the featured list". Then the "featured" list could be a lot bigger, and Atom would show the top N most relevant packages which are not already installed.

"Related" could be defined as "often used in combination with some other package you have installed".

I'm probably taking this idea way too far, aren't I? ;)

**Comment by winstliu** [comment]
That would be super cool.  I guess related package keywords could also factor in.  Though...it would also probably take a lot of effort to implement :laughing:.
