### ISSUE TITLE
All pathwatcher-related APIs are 404ing

### ISSUE THREAD

**Issue by winstliu** [atom/atom.io#83]
Any code link in https://atom.io/docs/api/v1.8.0/File or https://atom.io/docs/api/v1.8.0/Directory 404s.  The issue appears to be that the links are targeting node-pathwatcher@6.2.5, when in fact no such version exists (it goes 6.2.4 -> 6.3.0).

**Comment by Arcanemagus** [comment]
These links are currently working, both for the v1.8.0 linked here and the current v1.15.0.

**Comment by winstliu** [comment]
I meant the _code_ links, not the File link itself.  Those are still 404ing for v1.8.0.

**Comment by Arcanemagus** [comment]
Ah, sorry for the spam!

**Comment by jasonrudolph** [comment]
In https://github.com/atom/atom.io/issues/134, I [looked into](https://github.com/atom/atom.io/issues/134#issuecomment-358328461) fixing the broken links in Atom 1.8.0's docs, but it doesn't look like we have a viable solution. Please see that thread if you're interested in more details. 😅 

The good news is that these [links are fixed in the Atom 1.9.0 docs](https://atom.io/docs/api/v1.9.0/File).

Since Atom 1.9.0 came out about a year and a half ago, and since it fixes the broken links, and since we don't know of a viable fix for the Atom 1.8.0 links, I'm going to close this issue as "wontfix", and I'll continue looking into ways to prevent this in the future in https://github.com/atom/atom.io/issues/134.
