### ISSUE TITLE
"@media" sometimes change to "@"

### ISSUE THREAD

**Issue by ghost** [atom/atom.io#95]

**Comment by thomasjo** [comment]
First of all this has been opened on the wrong repo; this repo is specific to https://atom.io, not the editor itself. That repo is found at https://github.com/atom/atom.

Second, there is no functionality in a standard Atom installation does what you describe, so your problem is caused by one of your installed packages. If you need help tracking down the culprit, check out [Discuss](https://discuss.atom.io/) or our [Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
