### ISSUE TITLE
Website currently down

### ISSUE THREAD

**Issue by skull-squadron** [atom/atom.io#97]
https://uptime.com/atom.io

**Comment by skull-squadron** [comment]
Looks like a heroku worker is stuck/failed/DoS'ed.

**Comment by skull-squadron** [comment]
Up again, jiggity-jig.

**Comment by skull-squadron** [comment]
Intermittent connectivity.

**Comment by skull-squadron** [comment]
Seems up.

**Comment by nathansobo** [comment]
Heroku is experiencing an [API outage](https://status.heroku.com/incidents/963) due to a DDOS which is the most likely culprit. It is preventing us from logging in to view logs, preventing further diagnosis. Let's give the Heroku engineers time to resolve the issue and see if Atom.io recovers. It may be intermittent in the meantime.

**Comment by skull-squadron** [comment]
Grrr. Can't 4chan attack the GOP? 

Thanks for the update.

**Comment by skull-squadron** [comment]
Btw: might want to consider Fastly||CloudFlare as the FE to speed up the site, although it won't help Heroku (ec2).
